In [8]:
import numpy as np
from GAE.framasToGraph import FramsTransformer
pathframs = "/home/adam/Framsticks/Framsticks50rc19"

adjsize=15
frams_transf = FramsTransformer(pathframs,adjsize)
best_gen = '//0\np:2.298312727204787, 2.298312727204787, 2.298312727204787\np:1.0942442864477269, 3.8224330349472115, 2.298312727204787\np:0.7028104614021384, 4.270621270802676, 4.175778174543551\np:1.565672987248388, 3.759406037940308, 5.8569109926396425\np:1.4783265317666054, 4.289475890299355, 7.75219449408074\np:0.7772495399273303, 4.088782239960528, 9.58258642105356\np:4.29525112746713, 2.403939894437829, 2.298312727204787\np:1.391318972254275, 0.5160999449083605, 2.298312727204787\np:1.1953890754817635, 0.0, 4.190603268140904\np:1.3044577547232905, 0.0002276606071149878, 6.157922176447118\np:1.614924086010032, 0.32638985797429987, 8.017652350167477\np:1.7004047886718914, 0.7839183371053251, 9.930519748252479\nj:0, 1\nj:0, 6\nj:0, 7\nj:1, 2\nj:2, 3\nj:3, 4\nj:4, 5\nj:7, 8\nj:8, 9\nj:9, 10\nj:10, 11\n'
best_gen = frams_transf.getGrafFromString(best_gen)

Using Framsticks version: 5.0rc19.1
Home (writable) dir     : /home/adam/Framsticks/Framsticks50rc19/data
Resources dir           : /home/adam/Framsticks/Framsticks50rc19/data



In [10]:
best_gen.x

array([[ 2.29831273e+00,  2.29831273e+00,  2.29831273e+00],
       [ 1.09424429e+00,  3.82243303e+00,  2.29831273e+00],
       [ 7.02810461e-01,  4.27062127e+00,  4.17577817e+00],
       [ 1.56567299e+00,  3.75940604e+00,  5.85691099e+00],
       [ 1.47832653e+00,  4.28947589e+00,  7.75219449e+00],
       [ 7.77249540e-01,  4.08878224e+00,  9.58258642e+00],
       [ 4.29525113e+00,  2.40393989e+00,  2.29831273e+00],
       [ 1.39131897e+00,  5.16099945e-01,  2.29831273e+00],
       [ 1.19538908e+00,  0.00000000e+00,  4.19060327e+00],
       [ 1.30445775e+00,  2.27660607e-04,  6.15792218e+00],
       [ 1.61492409e+00,  3.26389858e-01,  8.01765235e+00],
       [ 1.70040479e+00,  7.83918337e-01,  9.93051975e+00],
       [-1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00, -1.00000000e+00, -1.00000000e+00]])

In [37]:
z = np.random.uniform(-1,1,size = (1,5))[0]
shift = np.random.uniform(-1,1,size = (1,5))[0]

In [15]:
z

array([[-0.82889165, -0.26145572,  0.38897131, -0.25549173,  0.70672827]])

In [16]:
-z

array([[ 0.82889165,  0.26145572, -0.38897131,  0.25549173, -0.70672827]])

In [14]:
shift

array([[ 0.47656895,  0.83720301, -0.05211388, -0.89686033,  0.03852479]])

In [17]:
-shift

array([[-0.47656895, -0.83720301,  0.05211388,  0.89686033, -0.03852479]])

In [54]:
z

array([ 0.3, -0. ,  0.3, -1. ,  0. ])

In [55]:
-z

array([-0.3,  0. , -0.3,  1. , -0. ])

In [56]:
shift

array([-0.8, -0. ,  0.2,  0.2, -0.5])

In [57]:
-shift

array([ 0.8,  0. , -0.2, -0.2,  0.5])

In [62]:
steps=21
finall = np.zeros(shape=(steps,steps,len(z)))

zs =  np.linspace(z,shift,steps)
nzns =  np.linspace(-z,-shift,steps)
for i in range(len(zs)):
    finall[i] = np.linspace(zs[i],nzns[-i],steps)

In [63]:
np.set_printoptions(precision=1)
print(finall[0])

[[ 0.3 -0.   0.3 -1.   0. ]
 [ 0.2 -0.   0.3 -0.9  0. ]
 [ 0.2 -0.   0.2 -0.8  0. ]
 [ 0.2 -0.   0.2 -0.7  0. ]
 [ 0.2 -0.   0.2 -0.6  0. ]
 [ 0.1 -0.   0.1 -0.5  0. ]
 [ 0.1 -0.   0.1 -0.4  0. ]
 [ 0.1 -0.   0.1 -0.3  0. ]
 [ 0.1 -0.   0.1 -0.2  0. ]
 [ 0.  -0.   0.  -0.1  0. ]
 [ 0.   0.   0.   0.   0. ]
 [-0.   0.  -0.   0.1 -0. ]
 [-0.1  0.  -0.1  0.2 -0. ]
 [-0.1  0.  -0.1  0.3 -0. ]
 [-0.1  0.  -0.1  0.4 -0. ]
 [-0.1  0.  -0.1  0.5 -0. ]
 [-0.2  0.  -0.2  0.6 -0. ]
 [-0.2  0.  -0.2  0.7 -0. ]
 [-0.2  0.  -0.2  0.8 -0. ]
 [-0.2  0.  -0.3  0.9 -0. ]
 [-0.3  0.  -0.3  1.  -0. ]]


In [45]:
 new = np.linspace(z,-z,steps)

array([[ 2.62e-01, -1.02e-02,  2.90e-01, -9.79e-01,  4.07e-02],
       [ 2.35e-01, -9.08e-03,  2.60e-01, -8.76e-01,  3.64e-02],
       [ 2.07e-01, -8.01e-03,  2.29e-01, -7.73e-01,  3.21e-02],
       [ 1.79e-01, -6.95e-03,  1.99e-01, -6.70e-01,  2.78e-02],
       [ 1.52e-01, -5.88e-03,  1.68e-01, -5.67e-01,  2.36e-02],
       [ 1.24e-01, -4.81e-03,  1.38e-01, -4.64e-01,  1.93e-02],
       [ 9.66e-02, -3.74e-03,  1.07e-01, -3.61e-01,  1.50e-02],
       [ 6.90e-02, -2.67e-03,  7.64e-02, -2.58e-01,  1.07e-02],
       [ 4.14e-02, -1.60e-03,  4.59e-02, -1.55e-01,  6.43e-03],
       [ 1.38e-02, -5.34e-04,  1.53e-02, -5.15e-02,  2.14e-03],
       [-1.38e-02,  5.34e-04, -1.53e-02,  5.15e-02, -2.14e-03],
       [-4.14e-02,  1.60e-03, -4.59e-02,  1.55e-01, -6.43e-03],
       [-6.90e-02,  2.67e-03, -7.64e-02,  2.58e-01, -1.07e-02],
       [-9.66e-02,  3.74e-03, -1.07e-01,  3.61e-01, -1.50e-02],
       [-1.24e-01,  4.81e-03, -1.38e-01,  4.64e-01, -1.93e-02],
       [-1.52e-01,  5.88e-03, -1.68e-01,